# Generated by Django 4.0.3 on 2022-03-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_event',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
