# Generated by Django 4.0.5 on 2022-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0002_event_deleted_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deleted_event',
        ),
        migrations.AddField(
            model_name='event',
            name='hidden_event',
            field=models.BooleanField(default=False, verbose_name='Hidden event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Event description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
