# Generated by Django 4.0.5 on 2022-06-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0003_remove_event_deleted_event_event_hidden_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hidden_event',
            new_name='hidden',
        ),
    ]
